// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A style recommendation AI agent.
 *
 * - getStyleRecommendation - A function that handles the style recommendation process.
 * - StyleRecommendationInput - The input type for the getStyleRecommendation function.
 * - StyleRecommendationOutput - The return type for the getStyleRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const StyleRecommendationInputSchema = z.object({
  measurements: z
    .record(z.string(), z.number())
    .describe('A record of the customer measurements (e.g., { chest: 38, waist: 32 }).'),
  orderHistory: z
    .string()
    .describe('The order history of the customer.'),
  preferences: z
    .string()
    .describe('The style preferences of the customer.'),
});
export type StyleRecommendationInput = z.infer<typeof StyleRecommendationInputSchema>;

const StyleRecommendationOutputSchema = z.object({
  styleRecommendation: z.string().describe('The style recommendation for the customer.'),
});
export type StyleRecommendationOutput = z.infer<typeof StyleRecommendationOutputSchema>;

export async function getStyleRecommendation(input: StyleRecommendationInput): Promise<StyleRecommendationOutput> {
  return getStyleRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'styleRecommendationPrompt',
  input: {schema: StyleRecommendationInputSchema},
  output: {schema: StyleRecommendationOutputSchema},
  prompt: `You are an expert fashion consultant. Based on the customer's measurements, order history, and preferences, you will provide a style recommendation.

Measurements: {{{measurements}}}
Order History: {{{orderHistory}}}
Preferences: {{{preferences}}}

Style Recommendation:`,
});

const getStyleRecommendationFlow = ai.defineFlow(
  {
    name: 'getStyleRecommendationFlow',
    inputSchema: StyleRecommendationInputSchema,
    outputSchema: StyleRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
